###################################################
###################################################
# Replicated Docs Redirects
###################################################
###################################################



###################################################
# Syntax
###################################################

#[[redirects]]
  #from = "FROM_URL"
  #to = "TO_URL"

# For more information, see https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

###################################################
# High-Level Redirects
###################################################


# Redirects from the root of the directories
[[redirects]]
  #from = "/*"
  #to = "/blog/:splat"
  # See https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

  from = "https://docs.replicated.com/vendor"
  to = "https://docs.replicated.com/"

[[redirects]]
  from = "https://docs.replicated.com/enterprise"
  to = "https://docs.replicated.com/enterprise/installing-overview"

[[redirects]]
  from = "https://docs.replicated.com/reference"
  to = "https://docs.replicated.com/reference/cron-expressions"

[[redirects]]
  from = "https://docs.replicated.com/release-notes"
  to = "https://docs.replicated.com/release-notes/rn-whats-new"

###################################################
# Redirects To the Getting Started Section
###################################################
[[redirects]]
  from = "https://docs.replicated.com/vendor/tutorial-installing-with-existing-cluster"
  to = "https://docs.replicated.com/vendor/tutorial-ui-setup"

[[redirects]]
  from = "https://docs.replicated.com/vendor/tutorial-installing-with-cli"
  to = "https://docs.replicated.com/vendor/tutorial-cli-setup"

[[redirects]]
  from = "https://docs.replicated.com/vendor/tutorial-installing-without-existing-cluster"
  to = "https://docs.replicated.com/vendor/tutorial-ui-setup"

###################################################
# Redirects To the Vendor Section
###################################################

[[redirects]]
  from = "https://docs.replicated.com/vendor/helm-chart-components"
  to = "https://docs.replicated.com/vendor/helm-optional-charts"

[[redirects]]
  from = "https://docs.replicated.com/vendor/packaging-custom-resources"
  to = "https://docs.replicated.com/vendor/releases-creating-releases"

[[redirects]]
  from="https://docs.replicated.com/vendor/tutorial-ha-cluster-deploying"
  to="https://docs.replicated.com/enterprise/installing-embedded-cluster#install-with-ha-in-online-environments"

[[redirects]]
  from="https://docs.replicated.com/vendor/tutorial-installing-air-gap-existing-cluster-gcp"
  to="https://docs.replicated.com/enterprise/installing-existing-cluster-airgapped"

[[redirects]]
  from="https://docs.replicated.com/vendor/releases-promoting"
  to="https://docs.replicated.com/vendor/releases-creating-releases"

[[redirects]]
  from="https://docs.replicated.com/vendor/packaging-private-registry-cname"
  to="https://docs.replicated.com/vendor/custom-domains"

[[redirects]]
  from="https://docs.replicated.com/vendor/releases-semantic-versioning"
  to="https://docs.replicated.com/vendor/releases-about"

[[redirects]]
  from="https://docs.replicated.com/vendor/helm-installing-native-helm"
  to="https://docs.replicated.com/vendor/helm-overview"

[[redirects]]
  from="https://docs.replicated.com/vendor/helm-processing"
  to="https://docs.replicated.com/vendor/helm-overview"

[[redirects]]
  from="https://docs.replicated.com/vendor/team-management-rbac-about"
  to="https://docs.replicated.com/vendor/team-management-rbac-configuring"

[[redirects]]
  from="https://docs.replicated.com/vendor/identity-service-configuring"
  to="https://docs.replicated.com/vendor/releases-creating-customer"
  
###################################################
# Redirects To the Enterprise Section
###################################################

[[redirects]]
  from="https://docs.replicated.com/enterprise/updating-existing-cluster"
  to="https://docs.replicated.com/enterprise/updating-app-manager" 

[[redirects]]
  from="https://docs.replicated.com/enterprise/snapshots-restoring-partial"
  to="https://docs.replicated.com/enterprise/snapshots-restoring-full"

[[redirects]]
  from="https://docs.replicated.com/enterprise/snapshots-scheduling"
  to="https://docs.replicated.com/enterprise/snapshots-creating" 

[[redirects]]
  from="https://docs.replicated.com/enterprise//snapshots-config-workflow"
  to="https://docs.replicated.com/enterprise/snapshots-velero-cli-installing"

[[redirects]]
  from="https://docs.replicated.com/enterprise/image-registry-airgap"
  to="https://docs.replicated.com/enterprise/installing-general-requirements"

[[redirects]]
  from="https://docs.replicated.com/enterprise/installing-app-setup"
  to="https://docs.replicated.com/enterprise/installing-existing-cluster#install-app"
   
###################################################
# Redirects To the References Section
###################################################

# Redirects from the removed packaging-template-functions topic
[[redirects]]
  from="https://docs.replicated.com/vendor/packaging-template-functions"
  to= "https://docs.replicated.com/reference/template-functions-about"

# Redirects from the old topic name KOTS Lint Rules to the new topic name Lint Rules
[[redirects]]
  from="https://docs.replicated.com/reference/kots-lint"
  to="https://docs.replicated.com/reference/linter"

###################################################
# Redirects To the Release Notes Section
###################################################



