###################################################
###################################################
# Replicated Docs Redirects
###################################################
###################################################



###################################################
# Syntax
###################################################

#[[redirects]]
  #from = "FROM_URL"
  #to = "TO_URL"

# For more information, see https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

###################################################
# High-Level Redirects
###################################################


# Redirects from the root of the directories
[[redirects]]
  #from = "/*"
  #to = "/blog/:splat"
  # See https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

  from = "https://docs.replicated.com/vendor"
  to = "https://docs.replicated.com/vendor/distributing-workflow"

[[redirects]]
  from = "https://docs.replicated.com/enterprise"
  to = "https://docs.replicated.com/enterprise/installing-overview"

[[redirects]]
  from = "https://docs.replicated.com/reference"
  to = "https://docs.replicated.com/reference/custom-resource-about"

[[redirects]]
  from = "https://docs.replicated.com/release-notes"
  to = "https://docs.replicated.com/release-notes/rn-whats-new"

###################################################
# Redirects To the Getting Started Section
###################################################
[[redirects]]
  from = "https://docs.replicated.com/vendor/tutorial-installing-with-existing-cluster"
  to = "https://docs.replicated.com/vendor/tutorial-ui-setup"

[[redirects]]
  from = "https://docs.replicated.com/vendor/tutorial-installing-with-cli"
  to = "https://docs.replicated.com/vendor/tutorial-cli-setup"

[[redirects]]
  from = "https://docs.replicated.com/vendor/tutorial-installing-without-existing-cluster"
  to = "https://docs.replicated.com/vendor/tutorial-ui-setup"

###################################################
# Redirects To the Vendor Section
###################################################

[[redirects]]
  from = "https://docs.replicated.com/vendor/packaging-custom-resources"
  to = "https://docs.replicated.com/vendor/releases-creating-releases"

###################################################
# Redirects To the Enterprise Section
###################################################

###################################################
# Redirects To the References Section
###################################################

# Redirects from the removed packaging-template-functions topic
[[redirects]]
  from="https://docs.replicated.com/vendor/packaging-template-functions"
  to= "https://docs.replicated.com/reference/template-functions-about"

###################################################
# Redirects To the Release Notes Section
###################################################
