on:
  pull_request:
    types: [opened]

name: Auto-label new PRs

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const labels = ['type::feature', 'type::docs']
            github.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels
            })
            